---
- name: Configure MySQL in Ubuntu
  hosts: test_servers
  become_method: sudo
  become: yes
  remote_user: root
  vars:
    mysql_root_password: dharani
    mysql_user: dharani
    mysql_user_password: dharani
    mysql_db: people
  tasks:
    - name: Install MySQL
      apt:
        update_cache: yes
        name:
          - mysql-server
          - mysql-client
          - php
          - php-mysql
        state: present

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Secure MySQL installation
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: ""

    - name: Create a database
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      
    - name: Insert data into MySQL table
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_user_password }}"
        login_host: localhost
        login_port: 3306
        login_db: "{{ mysql_db }}"
        query: "INSERT IGNORE INTO people (email, password) VALUES ('user1@gmail.com', 'user@12341');"

    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Start Apache Service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy index.html and index.php files
      copy:
        src: "{{ item.src }}"
        dest: /var/www/html/"{{ item.dest }}"
      with_items:
      - { src: "success.html", dest: "success.html.html" }
      - { src: "index.php", dest: "index.php" }
      

    - name: Restart Apache Service
      service:
        name: apache2
        state: started
        enabled: true
    
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy
      
  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted